# 游戏延迟配置文件
# Game Timing Configuration

# =============================================================================
# 游戏流程延迟配置 (Game Flow Timing)
# =============================================================================

# 基础动作延迟 - 玩家基础行动间隔 (秒)
action_delay: 1.0

# 发言延迟 - 每次玩家发言之间的间隔 (秒)
debate_delay: 1.0

# 夜间行动延迟 - 夜晚阶段技能执行的延迟 (秒)
night_action_delay: 1.0

# 总结延迟 - 阶段总结时的延迟 (秒)
summary_delay: 1.0

# =============================================================================
# 前端刷新配置 (Frontend Refresh Timing)
# =============================================================================

# 前端刷新间隔 - 界面自动刷新间隔 (毫秒)
frontend_refresh_interval: 5000

# 游戏状态刷新间隔 - 游戏状态检查间隔 (毫秒)
game_status_refresh_interval: 2000

# =============================================================================
# 动画和UI延迟配置 (Animation & UI Timing)
# =============================================================================

# 界面动画延迟 - UI动画效果延迟 (毫秒)
ui_animation_delay: 300

# 消息显示延迟 - 消息显示/隐藏延迟 (毫秒)
message_display_delay: 1000

# 页面切换延迟 - 页面切换动画延迟 (毫秒)
page_transition_delay: 500

# =============================================================================
# API和网络配置 (API & Network Timing)
# =============================================================================

# API请求超时 - API请求默认超时时间 (秒)
api_request_timeout: 30

# 重试延迟 - API请求失败后重试间隔 (秒)
retry_delay: 2.0

# 长连接心跳间隔 - WebSocket心跳间隔 (秒)
heartbeat_interval: 30

# =============================================================================
# 开发调试配置 (Development & Debug Timing)
# =============================================================================

# 开发模式快速刷新 - 开发环境下的快速刷新间隔 (毫秒)
dev_fast_refresh: 1000

# 调试信息显示间隔 - 调试信息更新间隔 (毫秒)
debug_info_interval: 500

# =============================================================================
# 特殊游戏模式配置 (Special Game Mode Timing)
# =============================================================================

# 快速游戏模式 - 快速游戏下的延迟倍数 (0.0-1.0)
fast_game_multiplier: 0.5

# 慢速游戏模式 - 慢速游戏下的延迟倍数 (1.0+)
slow_game_multiplier: 2.0

# 演示模式 - 演示模式下的延迟倍数
demo_mode_multiplier: 1.5